{"Functions": {"DestroyFailedException()": {"Returns": [], "Parameters": [], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs a DestroyFailedException with no detail message. A detail message is a String that describes this particular exception.", "history": "Added in API level 1", "FullName": "public DestroyFailedException ()"}, "DestroyFailedException(java.lang.String)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the detail message."]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs a DestroyFailedException with the specified detail message. A detail message is a String that describes this particular exception.", "history": "Added in API level 1", "FullName": "public DestroyFailedException (String msg)"}}, "Inheritance": ["@B_java#lang#Throwable_E@", "@B_java#lang#Exception_E@"], "ClassName": "javax.security.auth.DestroyFailedException", "ClassDesc": "Signals that a destroy operation failed. This exception is thrown by credentials implementing the Destroyable interface when the destroy method fails."}