{"Functions": {"CertStoreException(java.lang.Throwable)": {"Returns": [], "Parameters": [["@B_java#lang#Throwable_E@", "Throwable: the cause (which is saved for later retrieval by the @B_java#lang#Throwable#getCause_E@ method). (A null value is permitted, and indicates that the cause is nonexistent or unknown.)"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Creates a CertStoreException that wraps the specified throwable. This allows any exception to be converted into a CertStoreException, while retaining information about the cause, which may be useful for debugging. The detail message is set to (cause==null ? null : cause.toString()) (which typically contains the class and detail message of cause).", "history": "Added in API level 1", "FullName": "public CertStoreException (Throwable cause)"}, "CertStoreException(java.lang.String)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the detail message"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Creates a CertStoreException with the given detail message. A detail message is a String that describes this particular exception.", "history": "Added in API level 1", "FullName": "public CertStoreException (String msg)"}, "CertStoreException(java.lang.String,java.lang.Throwable)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the detail message"], ["@B_java#lang#Throwable_E@", "Throwable: the cause (which is saved for later retrieval by the @B_java#lang#Throwable#getCause_E@ method). (A null value is permitted, and indicates that the cause is nonexistent or unknown.)"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Creates a CertStoreException with the specified detail message and cause.", "history": "Added in API level 1", "FullName": "public CertStoreException (String msg, Throwable cause)"}, "CertStoreException()": {"Returns": [], "Parameters": [], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Creates a CertStoreException with null as its detail message.", "history": "Added in API level 1", "FullName": "public CertStoreException ()"}}, "Inheritance": ["@B_java#lang#Throwable_E@", "@B_java#lang#Exception_E@", "@B_java#security#GeneralSecurityException_E@"], "ClassName": "java.security.cert.CertStoreException", "ClassDesc": "An exception indicating one of a variety of problems retrieving certificates and CRLs from a CertStore. A CertStoreException provides support for wrapping exceptions. The @B_java#lang#Throwable#getCause_E@ method returns the throwable, if any, that caused this exception to be thrown. Unless otherwise specified, the methods defined in this class are not thread-safe. Multiple threads that need to access a single object concurrently should synchronize amongst themselves and provide the necessary locking. Multiple threads each manipulating separate objects need not synchronize."}