{"Functions": {"SSLException(java.lang.String,java.lang.Throwable)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the detail message (which is saved for later retrieval by the @B_java#lang#Throwable#getMessage_E@ method)."], ["@B_java#lang#Throwable_E@", "Throwable: the cause (which is saved for later retrieval by the @B_java#lang#Throwable#getCause_E@ method). (A null value is permitted, and indicates that the cause is nonexistent or unknown.)"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Creates a SSLException with the specified detail message and cause.", "history": "Added in API level 1", "FullName": "public SSLException (String message, Throwable cause)"}, "SSLException(java.lang.String)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: describes the problem."]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs an exception reporting an error found by an SSL subsystem.", "history": "Added in API level 1", "FullName": "public SSLException (String reason)"}, "SSLException(java.lang.Throwable)": {"Returns": [], "Parameters": [["@B_java#lang#Throwable_E@", "Throwable: the cause (which is saved for later retrieval by the @B_java#lang#Throwable#getCause_E@ method). (A null value is permitted, and indicates that the cause is nonexistent or unknown.)"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Creates a SSLException with the specified cause and a detail message of", "history": "Added in API level 1", "FullName": "public SSLException (Throwable cause)"}}, "Inheritance": ["@B_java#lang#Throwable_E@", "@B_java#lang#Exception_E@", "@B_java#io#IOException_E@"], "ClassName": "javax.net.ssl.SSLException", "ClassDesc": "Indicates some kind of error detected by an SSL subsystem. This class is the general class of exceptions produced by failed SSL-related operations."}